### ISSUE TITLE
Unhandled exception while creating AQ15 model

### ISSUE THREAD

**Issue by AsiaHenzel** [awojna/Rseslib#8]
Hello!

Currently, I am trying to generate rule-based models using the AQ15 algorithm. For some datasets, I encounter a `NullPointerException`. After some debugging, I have identified the issue.

I am using the rseslib library by importing the Java package. I create my model using the following function:

```java
DoubleDataTable trainTable = new ArrayListDoubleDataTable(new File(trainPath), new EmptyProgress());
...
AQ15Classifier aq15 = new AQ15Classifier((Properties) null, trainTable, prog);
```

When running `AQ15Classifier()` I got the error. This creator runs `generate(DoubleDataTable tab, Progress prog)` from class `CoveringRuleGenerator`.  In this `generate` function, the `generate` function from `AQ15OneRuleGenerator` is started. 
In the function `generate` from `AQ15OneRuleGenerator` there is a code:

```java
Rule rule = null;
if (candidates.size() > 0) {
   rule = new BooleanFunctionRule((BooleanFunction)candidates.get(0), e_pos.getDecision(), examples.attributes().nominalDecisionAttribute());
}

return rule;
```

For some dataset the `candidates.size()` is equal `0` and this function returns `null`. This value goes back to `generate` function from `CoveringRuleGenerator`, where there is a code:

```java
for(int prooningObjts = uncovered.size(); (double)uncovered.size() > this.m_prooning * (double)prooningObjts; uncovered = this.removeCovered(uncovered, rules)) {
  rules.add(this.m_oneRuleGenerator.generate(tab, uncovered, this.m_k, dec));
}
```

For example, after some iterations I got `rules` object that looks like this:

![AQ15_reguly](https://github.com/awojna/Rseslib/assets/18016634/be2fa054-3e47-4ad0-b4f2-6896c8248758)

We can see that the last added rule is `null`. Then, the function `uncovered = this.removeCovered(uncovered, rules)` is started (this execution is inside the above `for` loop). The `removeCovered` function is called with the rules object, which has a null value, resulting in a `NullPointerException`.

Can I do something that will eliminate the `NullPointerException` error?

I add simple code and dataset for which the problem occurs.

[AQ15ErrorExample.zip](https://github.com/awojna/Rseslib/files/14194401/AQ15ErrorExample.zip)

**Comment by awojna** [comment]
Hello Joanna,

Thank you very much for your investigation and detailed information on the issue, that significantly sped up the fix. The fix is already in the master branch of Rseslib repository in GitHub.

Is it ok for you to check out and use the fixed Rseslib source from GitHub?

Arek

**Comment by AsiaHenzel** [comment]
Hello,

I've checked the performance of the new version of Rseslib on the example dataset - the model built correctly. The NullPointerException no longer occurs. Thank you for your help. In the near future, I will also run the algorithm on a larger number of datasets and I will verify that everything works correctly there too. For now I will clode the issue.

Best regards
Joanna

**Comment by awojna** [comment]
I'm glad to hear that, thank you for the check.

Arek
